DELIMITER $$
CREATE FUNCTION IF NOT EXISTS validemail(correo VARCHAR(50))
	RETURNS BOOLEAN DETERMINISTIC
	BEGIN 
    RETURN IF (correo REGEXP '^[a-zA-Z0-9]+((\.[a-zA-Z0-9]+)|(\_[a-zA-Z0-9]+))?@[a-zA-Z]+(\.[a-zA-Z]+)+$',true,false);
    
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION IF NOT EXISTS sololetras(str VARCHAR(35))
	RETURNS BOOLEAN DETERMINISTIC
	BEGIN
	RETURN IF (str REGEXP '^[a-zA-Zaáéíóú]*$',true,false);
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION IF NOT EXISTS esPositivo(num INT)
	RETURN BOOLEAN DETERMINISTIC
	BEGIN
	IF num>=0 THEN
		RETURN 1;
	ELSE
		RETURN 0;
	END IF;
END $$
DELIMITER ;

#Si detecta numero mayores que 0
DELIMITER $$
CREATE FUNCTION IF NOT EXISTS esEntero(num INT)
	RETURN BOOLEAN DETERMINISTIC
	BEGIN
	IF num>0 THEN
		RETURN 1;
	ELSE
		RETURN 0;
	END IF;
END $$
DELIMITER ;
	
DELIMITER $$
CREATE FUNCTION IF NOT EXISTS existciclo(cl VARCHAR(2))
	RETURNS BOOLEAN DETERMINISTIC
	BEGIN 
	IF cl='1S' THEN
		RETURN 1;
	ELSEIF cl='2S' THEN
		RETURN 1;
	ELSEIF cl='VJ' THEN
		RETURN 1;
	ELSEIF cl='VD' THEN
		RETURN 1;
	ELSE
		RETURN 0;
	END IF;
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION IF NOT EXISTS isFecha(dt VARCHAR(12))
	RETURNS BOOLEAN DETERMINISTIC
	BEGIN
	RETURN IF (dt REGEXP '^[0-9]{1,2}:[0-9]{2}-[0-9]{1,2}:[0-9]{2}$',true,false)
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION IF NOT EXISTS isDia(dia INT)
	RETURNS BOOLEAN DETERMINISTIC
	BEGIN
	IF dia>0 AND dia<8 THEN
		RETURN 1;
	ELSE
		RETURN 0;
	END IF;
END $$
DELIMITER ;